name: cutap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cloud_firestore: ^4.17.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  go_router: ^14.0.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  quickalert: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
