// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzisNZZF6dVHFcuEIzq_Y7LeyPtexXxgU',
    appId: '1:50254635250:web:a345a71448052ff068f06b',
    messagingSenderId: '50254635250',
    projectId: 'admin-users-cuptap',
    authDomain: 'admin-users-cuptap.firebaseapp.com',
    storageBucket: 'admin-users-cuptap.appspot.com',
    measurementId: 'G-YZRQ2WKPFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ev9Qk_l9HgPPQYWe1VynnWjsHllP1MY',
    appId: '1:50254635250:android:0e31fa250af3113068f06b',
    messagingSenderId: '50254635250',
    projectId: 'admin-users-cuptap',
    storageBucket: 'admin-users-cuptap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgJ4xqv7OXyBkUFQBufUW_mc7__4TBx6I',
    appId: '1:50254635250:ios:745bcd4c13bc268c68f06b',
    messagingSenderId: '50254635250',
    projectId: 'admin-users-cuptap',
    storageBucket: 'admin-users-cuptap.appspot.com',
    iosBundleId: 'com.example.cutap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgJ4xqv7OXyBkUFQBufUW_mc7__4TBx6I',
    appId: '1:50254635250:ios:745bcd4c13bc268c68f06b',
    messagingSenderId: '50254635250',
    projectId: 'admin-users-cuptap',
    storageBucket: 'admin-users-cuptap.appspot.com',
    iosBundleId: 'com.example.cutap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzisNZZF6dVHFcuEIzq_Y7LeyPtexXxgU',
    appId: '1:50254635250:web:00bfebf646841d9068f06b',
    messagingSenderId: '50254635250',
    projectId: 'admin-users-cuptap',
    authDomain: 'admin-users-cuptap.firebaseapp.com',
    storageBucket: 'admin-users-cuptap.appspot.com',
    measurementId: 'G-Z5X7SZXLKC',
  );
}
